### ISSUE TITLE
Option to store virtualenv in a project directory?

### ISSUE THREAD

**Issue by yoshihikoueno** [MichaelAquilina/zsh-autoswitch-virtualenv#102]
this is not an "issue" but more like a feature request.

Currently, this plugin will store all the virtualenvs in one directory no matter where the project is located. Although it doesn't cause problems in many cases, in some rare cases, it does.

1. The same project name in different directories.
2. Forget to "rmenv" before deleting a project directory.

As a virtualenv is meant to be an environment which is specific to a project, it would make more sense and intuitive to have virtualenvs in a project directory.
If we finish working on a project and delete the directory, the virtualenv will also be deleted automatically together.

More importantly, if we move a project directory to another computer, then the virtualenv will be shipped together with the project. I think there are so many benefits of having a vitualenv in a project directory. Why not?

**Comment by rnc** [comment]
Potentially related to #66 ? Surely when utilising an SCM you would not copy the directory but check it out again - and given the python installations could be different, the virtual env may not apply? Personally, even if this was implemented, I would prefer it to be an option and not the default :-)

**Comment by yoshihikoueno** [comment]
Hmm, true. But I still wonder. What is the advantage of having virtualenv in a separated directory?

**Comment by rnc** [comment]
@yoshihikoueno Ok this is **personal** opinion so everyone else may differ :-) This means my venvs are not split across the disk but kept in a single location. They don't 'pollute' the checkout with unnecessary files. Note I often use `mkvenv --system-site-packages` as I inherit system installed RPM packages. 

Have you seen under options (https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv#options) that you can use `AUTOSWITCH_VIRTUAL_ENV_DIR` to customise the location? So you could set that to your checkout directory? (and the fact that https://virtualenvwrapper.readthedocs.io/en/latest uses this location)

**Comment by yoshihikoueno** [comment]
Thanks, yeah, it makes sense. I guess it's just a matter of our preferences and working environments.

Also, thank you for suggesting of the option. However, I believe that it's static. So if I want my virtualenvs to be located on a project dir, I would probably need to dynamically change `AUTOSWITCH_VIRTUAL_ENV_DIR` so that it'll point the current project dir.

I guess I can just fork this project and modify it to meet my preferences.
Thank you for your time.

**Comment by rnc** [comment]
@yoshihikoueno Why not either use a wrapper or, possibly even neater a `chpwd` hook, to modify that variable upon changing directory to the new directory ?

**Comment by yoshihikoueno** [comment]
Yes, that's basically what I did.

https://github.com/yoshihikoueno/zsh-autoswitch-virtualenv

**Comment by MichaelAquilina** [comment]
Creating virtualenvs in the home directory is basically what `virtualenvwrapper` does. I've emulated this behaviour because once this project used virtualenvwrapper (but then removed it because it was very slow). 

I think having an option to create virtualenvs in the same place as the source code is perfectly fine to have :) @yoshihikoueno feel free to open a PR if you wish. I can add the option myself too but I am currently a bit constrained for available time so cant promise a quick delivery.

**Comment by hmoffatt** [comment]
I would like this too, as it would allow the virtualenv to be shared among users. We have projects deployed to production which have a virtualenv in the same directory. I update it as my user, and it runs as the web server, so I need the virtualenv in a location that can be shared by both.

This is possible with the dotpyvenv plugin (https://github.com/jeanpantoja/dotpyvenv), but that plugin is more basic and doesn't automatically create the venv for you if it's missing.

**Comment by MichaelAquilina** [comment]
I just realised that his feature is actually already supported, but not documented anywhere since I never really thought of it's use case.

Please try setting the following variable in your `zshrc`:

```
export AUTOSWITCH_VIRTUAL_ENV_DIR=".virtualenv"
```

Once that is set you should notice that all your virtualenvs will be stored in the directory where the `mkvenv` command is run.

Let me know if that satisfies your use case @yoshihikoueno

**Comment by yoshihikoueno** [comment]
@MichaelAquilina Thank you for letting me know about that! That feature is exactly what I wanted!

**Comment by MichaelAquilina** [comment]
Marking this issue as closed then, thanks for confirming!
