### ISSUE TITLE
.venv directory

### ISSUE THREAD

**Issue by pawnhearts** [MichaelAquilina/zsh-autoswitch-virtualenv#111]
# Issue Details

When pipenv is configured to create virtualenvs in project directories it stores them in .venv directories. That breaks plugin.

My workaround for that:
https://paste.ubuntu.com/p/4zHqwVFMvQ/

**Comment by MichaelAquilina** [comment]
@pawnhearts as a temporary workaround please download the latest version (1.15.0) and set the value of `AUTOSWITCH_FILE` to something other than `.venv`. For example:

```
export AUTOSWITCH_FILE=".autoswitch_venv"
```
