### ISSUE TITLE
Tab/Window title is set incorrectly due to MYOLDPWD

### ISSUE THREAD

**Issue by wookayin** [MichaelAquilina/zsh-autoswitch-virtualenv#19]
This is a weird bug report, but I don't think zsh-autoswitch-virtualenv is responsible for this. Let me explain what happens:

![image](https://user-images.githubusercontent.com/1009873/28905804-0e8603cc-784e-11e7-859d-da216addd1c0.png)

As shown in the figure, the tab/window title of zsh shell reads `~MYOLDPWD` (see Tab 1), which shall be a valid path, `~/.zplug/repos/sorin-ionescu/...`. Please note that this feature is from [prezto's `terminal` module]( https://github.com/sorin-ionescu/prezto/blob/master/modules/terminal/init.zsh#L66) (or similar plugins from zsh frameworks). `MYOLDPWD` is definitely a thing from zsh-autoswitch-virtualenv.

In `autoswitch_virtualenv.plugin.zsh`, there is a line in which an env-var `MYOLDPWD` is being set. However, if we remove this line, this bug doesn't happen anymore (we have the correct title)!
```diff
 # Automatically switch virtualenv when .venv file detected
 function _check_venv()
 {
     if [ "$PWD" != "$MYOLDPWD" ]; then
-       MYOLDPWD="$PWD"

        SWITCH_TO=""
```

I think it is very weird! One interesting thing is that if we use another name, such as `FOOBAR="$PWD"` or `CONSTANT=1`, these name occur in the tab title instead.

It's more plausible that `zsh` or `prezto` is reponsible for this behavior (maybe conflicts?), but any recent versions of them didn't resolve the issue. Maybe we could find some workaround for this bug. Any idea why it does happen?

**Comment by wookayin** [comment]
Some random findings:

There are two lines of registering zsh hooks; I am not sure why there are two (one with `-D` and one without), but if I remove the second line the bug does not happen (with `MYOLDPWD` kept intact). a bit confused..

```
 add-zsh-hook -D precmd _check_venv
-add-zsh-hook precmd _check_venv
```

**Comment by MichaelAquilina** [comment]
This indeed is a weird bug :thinking: 

for your second comment, the first line deletes any possible hooks that exist with the name "_check_venv" and the second line adds the hook back in. The first line is there in the case you would source the file a second time within the same session.

I will try find some information on why this could possibly happen. I dont seem to have this problem myself. Have you tried a different terminal emulator?

**Comment by wookayin** [comment]
Hi, thanks for your feedback. So the first line only removes, not adds the hook; thus we need both, right?

It happens in both of my iTerm2 and Terminal.app; not only my local mac machine, but also any linux machines over ssh.

**Comment by MichaelAquilina** [comment]
Could you possibly post your `.zshrc` to a gist?

**Comment by wookayin** [comment]
Please refer to my dotfiles repository: [`zshrc`](https://github.com/wookayin/dotfiles/blob/master/zsh/zshrc).

**Comment by MichaelAquilina** [comment]
I'll be away this weekend but I'll try give this a look as soon as I have the chance :)

**Comment by MichaelAquilina** [comment]
Hi @wookayin. Started looking at this again. Does this issue still show without your `.zshrc` file? Could you try renaming it and seeing if a new shell would still show this issue?

```
mv ~/.zshrc ~/.zshrc.bak
```

**Comment by wookayin** [comment]
Without some configuration from the zshrc applied, tab title would be never set. However, in the following minimal working example, I see the bug doesn't happen.

```zsh
% # Minimal zsh without any zshrc
% source ~/.zpreztorc
% source ~/.zprezto/modules/terminal/init.zsh      # activate terminal module to set title
% source ~/.zplug/repos/MichaelAquilina/zsh-autoswitch-virtualenv/autoswitch_virtualenv.plugin.zsh          # load zsh-autoswitch-virtualenv
```

I guess there is some weird conflict in my configuration; I'll have to locate it and why.

**Comment by MichaelAquilina** [comment]
I'm not familiar with the terminal module. Could you link me to any documentation behind it and maybe explain what it does to provide me some context?

**Comment by santiycr** [comment]
OK, I tracked down this issue and it came down to prezto default modules messing up with the prompt. It tries to be nice and show you env vars in your prompt if they exist pointing to your current directory. Here's the code:
https://github.com/sorin-ionescu/prezto/blob/master/modules/directory/init.zsh#L19

To fix it, add this to the bottom of your .zshrc:
```
unsetopt AUTO_NAME_DIRS       # Don't auto add variable-stored paths to ~ list.
```

**Comment by wookayin** [comment]
@santiycr Awesome, yeah that was the reason!

Some related zsh documentation: http://zsh.sourceforge.net/Doc/Release/Options.html#index-AUTOPARAMKEYS

I think an idea that was used in nojhan/liquidprompt#124 can be applied in our case as well. Basically we can prefix the string value stored in `MYOLDPWD` with some markers, so that this variable can be excluded from auto-naming. Let me prepare a PR soon.

**Comment by santiycr** [comment]
Oh yeah, great idea. Adding some prefix to the value and then extracting it would be all you need for zsh prompts to ignore it

**Comment by MichaelAquilina** [comment]
@santiycr thanks for investigating :) @wookayin looking forward to seeing that PR!

**Comment by MichaelAquilina** [comment]
Please test the latest version (0.3.2) and see if this is still an issue :) 

Sorry this took so long to fix!

**Comment by wookayin** [comment]
LGTM, thanks!
