### ISSUE TITLE
Does this plugin support python3 venv module?

### ISSUE THREAD

**Issue by yifeikong** [MichaelAquilina/zsh-autoswitch-virtualenv#24]
Is this a plugin for virtualenv package or python3 venv?

**Comment by MichaelAquilina** [comment]
Its for virtualenv. I'm not sure what python3 venv is?

**Comment by mralext20** [comment]
python3.3 ships with a module called venv, and it does basicly the same thing as virtualenv, except its bundled with the standard library.

**Comment by ankitp4t3l** [comment]
For posterity, the answer to OP is "no", correct?

**Comment by MichaelAquilina** [comment]
> For posterity, the answer to OP is "no", correct?

Correct. At the very least, the plugin hasnt been built with this module in mind. If someone does manage to get it working its just a happy coincidence :)
