### ISSUE TITLE
Command not found: virtualenv_deactivate

### ISSUE THREAD

**Issue by Ionaru** [MichaelAquilina/zsh-autoswitch-virtualenv#27]
When entering a directory with a virtualenv I created with `mkvenv` I get the output:
```
Switching virtualenv: testdir  deactivate:12: command not found: virtualenv_deactivate
[Python 2.7.14]
```

I have virtualenvwrapper installed and added to `.zshrc` with `source /usr/share/virtualenvwrapper/virtualenvwrapper.sh`

Activating and deactivating the virttualenv does work.

**Comment by MichaelAquilina** [comment]
That's strange.

What platform are you running on? What's you zsh version?

what does the output of `virtualenv_deactivate` give you?

**Comment by Ionaru** [comment]
Linux Kubuntu 17.10
zsh 5.2

Running the command virtualenv_deactivate inside a virtualenv will not output anything, just deactivates the virtualenv.
When running it outside a virtualenv I get the same error as above: `zsh: command not found: virtualenv_deactivate`

I am also getting the error when activating a virtualenv that was not made with `mkvenv`, but it never happened before installing zsh-autoswitch-virtualenv.

**Comment by MichaelAquilina** [comment]
could you post your `~/.zshrc` to a gist and link it here please?

**Comment by Ionaru** [comment]
Here you go: https://gist.github.com/Ionaru/d38c64f87d90ddeabab36fb8f30f095b

**Comment by wookayin** [comment]
I sometimes bumped into this when the environment variable `VIRTUAL_ENV` was just set (or inheritted from parent process, such as tmux).

**Comment by MichaelAquilina** [comment]
@Ionaru any update on this? What @wookayin said is true, if the `VIRTUAL_ENV` variable is set, but no actual virtualenv is activated, then this would explain the behaviour.

Perhaps some steps you take to get to that error message would help debug this?

**Comment by Ionaru** [comment]
The `VIRTUAL_ENV` variable wasn't set, as you can see in my `.zshrc` I check if it's set and call `deactivate` if it is.

My steps were simple, I  opened a new terminal and `cd`-ed to a directory with a virtualenv

**Comment by MichaelAquilina** [comment]
Closing this issue as this project no longer depends on `virtualenvwrapper` which is the source of the problem. Please try out the latest version of this plugin and open a new issue if any other problem arises :)
