### ISSUE TITLE
Does automatically deactivating venv makes sense?

### ISSUE THREAD

**Issue by wookayin** [MichaelAquilina/zsh-autoswitch-virtualenv#3]
The README reads:

> Moving out of the directory will automatically deactivate the virtual environment.

and indeed the plugin behaves so. However, I don't agree it does make sense. For example, suppose a project is structured as follows:

```
.venv
REAMDE.md
my_package/__init__.py
my_package/...
```

The virtualenv automatically gets activated according to `.venv`, but whenever we enter into another directory, including its subdirectories (`my_package` in this example), it gets deactivated. In most of use cases, one would expect working with these subpackages should be in the same virtualenv.

How would you think of this behavior? 
Thank you,

**Comment by MichaelAquilina** [comment]
Hi @wookayin. I agree moving to project subdirectories should not deactivate the virtualenv. However I do feel that moving out of the project should deactivate it. Perhaps we can come up with something that solves this specific case. If you want to give this a shot feel free to open a PR :)

**Comment by MichaelAquilina** [comment]
@wookayin I've opened a PR with a proposed solution. Could you test it out and see if this works for you? Its a pretty quick change so if you find any bugs let me know and I'll see what I can do.

**Comment by wookayin** [comment]
Hi @MichaelAquilina, thanks for your feedback. The suggestion #4 looks good as a default behavior and it works well.

Besides, I also think some might want to keep the virtualenv activated while moving out of the project, for temporarily or some of specific use cases. I suggest we can add a configuration point to customize the behavior.

**Comment by MichaelAquilina** [comment]
could you provide me an example scenario so that I can consider the problem?

**Comment by wookayin** [comment]
Well, the following is an artificial example, but how do you think of this:

```
(my_venv) ~/myproject/$ cd my_package/sub_package
(my_venv) ~/myproject/my_package/sub_package $ python ...
# ... do some work ...
(my_venv) ~/myproject/my_package/sub_package $ cd /data/some_dataset/
# deactivated
/data/some_dataset/ $ ...
# after getting work temporarily on the data dir, now go back to the project dirs
/data/some_dataset/ $ cd -
~/myproject/my_package/sub_package $ 
```

**Comment by MichaelAquilina** [comment]
hmmm this is a pretty remote case I think, and you could always just reactivate the virutalenv with `workon my_venv` to correct the situation. In the vast majority of cases, you would want the virtualenv to deactivate since you are exiting the project (which is the point of the project)>

**Comment by ccheek21** [comment]
I run into this fairly often when I'm switching into a project directory that isn't the project root directory. Does it make sense to look in parent directories for a .venv file too?

**Comment by ccheek21** [comment]
I just created pull request #13 that attempts to fix this problem

**Comment by MichaelAquilina** [comment]
@wookayin please test this out. Will be closing the issue. If you see that the issue has not been fixed feel free to re-open.

**Comment by wookayin** [comment]
Yeah, great job @ccheek21 and @MichaelAquilina! LGTM 👍
