### ISSUE TITLE
virtualenvwrapper required message

### ISSUE THREAD

**Issue by adi27** [MichaelAquilina/zsh-autoswitch-virtualenv#34]
After upgrading from 0.2.1 to 0.3.0, I see following message when I create new shell 
> zsh-autoswitch-virtualenv requires virtualenvwrapper to be installed! If this is already installed but you are still seeing this message, add the following to your ~/.zshrc:
> source =virtualenvwrapper.sh

And then my virtualenvs does not switch automatically if I change directory. The problem is that required line was there even before the update and was untouched after. My virtualenvwrapper works correctly. After downgrading to 0.2.1 everything works good.

**Comment by MichaelAquilina** [comment]
Interesting that you get this message.

Could you post the following:
- your OS and Distro name
- what `echo =virtualenvwrapper.sh` gives you
- what `find / -name "virtualenvwrapper" 2>/dev/null` returns

**Comment by adi27** [comment]
-   **your OS and Distro name**
Description:    Manjaro Linux
Release:        17.1.8
-    **what echo =virtualenvwrapper.sh gives you**
/usr/bin/virtualenvwrapper.sh
-    **what find / -name "virtualenvwrapper" 2>/dev/null returns**
/usr/lib/python3.6/site-packages/virtualenvwrapper
/home/\<user\>/.zplug/repos/robbyrussell/oh-my-zsh/plugins/virtualenvwrapper
/home/\<user\>/.local/lib/python2.7/site-packages/virtualenvwrapper

**Comment by MichaelAquilina** [comment]
Thanks @adi27 

what about the output of `which workon`.

Something to keep in mind is that `virtualenvwrapper` needs to be sourced before the plugin is loaded in order for it to work. Read here: https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv#requirements

**Comment by adi27** [comment]
That's exactly what I've just discovered when I was fixing my zshrc configuration, virtualenvwrapper has to be loaded before zplug plugin. Thanks for your help and I'm sorry for not paying enough attention to README file.

**Comment by MichaelAquilina** [comment]
I've updated the help message to hopefully make this more clear in #35
