### ISSUE TITLE
Is it possible to reduce 600 permission check to 644?

### ISSUE THREAD

**Issue by gugu** [MichaelAquilina/zsh-autoswitch-virtualenv#40]
# Issue Details

Current check for 600 permission does not add additional security and breaks some software from working (for example - ubuntu snaps and circleci local cli).

Example:

    ====>> Checkout code
    #!/bin/sh
    mkdir -p /home/circleci/project && cp -r /tmp/_circleci_local_build_repo/. /home/circleci/project
    cp: cannot open '/tmp/_circleci_local_build_repo/./.venv' for reading: Permission denied
    Error: Exited with code 1
    Step failed
    ====>> Uploading test results

How important is disabling reading a file? It does not contain anything secure.

Can I create a pull request for checking only write permissions for a file?

## Operating System (uname -a)

Linux andriibook 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## zsh version (zsh --version)

zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

## autoswitch-virtualenv version (echo "$AUTOSWITCH_VERSION")

0.3.4

## How is zsh-you-should-use installed?

- [ ] zplug
- [ ] oh-my-zsh
- [x] Antigen
- [ ] Other (please specify)

## Steps to reproduce the issue

create .venv file

**Comment by MichaelAquilina** [comment]
> How important is disabling reading a file? It does not contain anything secure.
The vector of attack is this.

If I am a user on your machine, and I have write access to your venv file. I can:
* create a virtualenv (e.g. "badenv") and insert malicious scripts
* write to your .venv file so that it points to "badenv"

Now whenever you change to that directory, you will be executing modules from malicious scripts.

Having said that - this assumes the ability to write not read -so we could potentially change that.

What user is being used by the example scripts you are running?

**Comment by gugu** [comment]
It uses root user (but from inside docker container with readonly mounted project directory). Same thing will be with other docker builds

**Comment by gugu** [comment]
No, it is on host machine. But curcleci cli tries to copy files from the
directory from the docker container

On Wed, Aug 1, 2018, at 7:23 PM, Michael Aquilina wrote:
> Is the plugin installed within the docker container?


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv/issues/40#issuecomment-409634013

**Comment by MichaelAquilina** [comment]
associated PR: #41

**Comment by MichaelAquilina** [comment]
do you have docker configured to run with the `docker` user group? (I am just trying to figure out what the minimum set of permissions you need are)

**Comment by gugu** [comment]
Yes, I have. But it is about connecting to docker server.

The problem is when docker container tries to copy files. And it uses user id of a container, not of the host

**Comment by MichaelAquilina** [comment]
Closing this issue as it was fixed by #41
