### ISSUE TITLE
Different projects with same folder name will conflict

### ISSUE THREAD

**Issue by MichaelAquilina** [MichaelAquilina/zsh-autoswitch-virtualenv#66]
e.g. `~/Development/foo` and `~/Projects/foo` would conflict with the same name when running `mkvenv`

**Comment by rnc** [comment]
Could a UUID be used either as `$HOME/.virtualenv/UUID/<env>` or as `.virtualenv/<venv>-UUID` ? Obviously would complicate the parsing and layout but would at least make them unique?

**Comment by MichaelAquilina** [comment]
The latter is deff something I would prefer.

I have not seen anyone complain about this specific issue though so I don't think it's as common as you think it would be.

Does this affect you @rnc ?

**Comment by rnc** [comment]
No I've not seen it (yet ;-) ).

**Comment by MichaelAquilina** [comment]
From #105 we can easily append uids to each virtualenv name now. 

What is not totally clear to me is how to be backwards compatible with non-uids venv names. We can probably use a workaround to identify them. Something like:

`project-name-ID=<uid>` where the `ID=` is pretty easily recognizable and testable.

**Comment by salmannotkhan** [comment]
What if while generating the venv we check if any venv with same name exists or not. If it does we can append the name with something that is more recognizable than pwgen output

**Comment by MichaelAquilina** [comment]
This issue should actually be solved in the latest release :) please upgrade and let me know if you are still having issues!

**Comment by MichaelAquilina** [comment]
> What if while generating the venv we check if any venv with same name exists or not. If it does we can append the name with something that is more recognizable than pwgen output

we could take that as an improvement for the future - but is there a reason why you dont like the `pwgen` output at the end? We could also take the approach of hiding it - but I'm not sure that is any better

**Comment by salmannotkhan** [comment]
>  but is there a reason why you dont like the pwgen output at the end?
There is it looks ugly. Many programmer like me care so much about clean names and can't tolerate some gibberish on terminal all the time XD

**Comment by MichaelAquilina** [comment]
we could probably create an optional feature to hide the pwgen name at the end. Feel free to take a go at it if you want :)

**Comment by salmannotkhan** [comment]
Yeah that is also good idea. Something like an environment variable "ZSH_AUTOSWITCH_CLEAN_NAMES"  :)

**Comment by salmannotkhan** [comment]
and is there any preference for which delimiter to use?

**Comment by salmannotkhan** [comment]
ok code is ready to do that once you tell which delimiter to use i'll do it :)
