### ISSUE TITLE
command not found: mkvenv

### ISSUE THREAD

**Issue by glebmikulko** [MichaelAquilina/zsh-autoswitch-virtualenv#67]
# Issue Details
After following installation guide for oh-my-zsh (cloning repo & adding plugins in ~/.zshrc), get error:
`zsh: command not found: mkvenv`
Please provide the following details when opening an issue:

## Operating System (uname -a)
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
## zsh version (zsh --version)
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
## autoswitch-virtualenv version (echo "$AUTOSWITCH_VERSION")
empty
## How is zsh-you-should-use installed?

- [ ] zplug
- [x] oh-my-zsh
- [ ] Antigen
- [ ] Other (please specify)

## Steps to reproduce the issue
mkvenv
## gist link to your zshrc
https://gist.github.com/glebmikulko/fcce11e0c5e0778fcafc7b784d87fe61

**Comment by glebmikulko** [comment]
Sure
```
$ echo $ZSH_CUSTOM/custom/plugins
/home/gleb/.oh-my-zsh/custom/custom/plugins
```
```
$ ls $ZSH_CUSTOM/custom/plugins
ls: cannot access '/home/gleb/.oh-my-zsh/custom/custom/plugins': No such file or directory
```

**Comment by MichaelAquilina** [comment]
right, seems like perhaps there is a mistake in the README (I don't use oh-my-zsh myself I am afraid).

But it does seem like (from what I understand) this plugin is installed in the correct location. 

could you provide the output of `echo $plugins`?

**Comment by glebmikulko** [comment]
```

**Comment by MichaelAquilina** [comment]
from what I can tell this should be working as normal. Have you tried installing any other custom plugin to oh-my-zsh? Has it worked?

I'm sorry I cant be of more help - I use `zplug` :/

**Comment by dcecile** [comment]
Same setup over here and same problem (oh-my-zsh custom plugin, cannot find mkvenv), but I found a basic fix.

By renaming `autoswitch_virtualenv.plugin.zsh` in the plugin folder to `autoswitch-virtualenv.plugin.zsh`, I was able to get the plugin to initialize. The mkvenv command works for me now, and so does auto-activation of pipenv's Pipfile.

I think that oh-my-zsh needs the plugin file name to match the folder name, including the dash. I'm not sure if this change would cause problems for other plugin install methods though...

**Comment by MichaelAquilina** [comment]
@glebmikulko could you check if the suggested fix works for you? If it does I could try apply the change to the entire repo to fix it for everyone.

Thanks for the help @dcecile :)

**Comment by glebmikulko** [comment]
Yes, it fixed my issue. Thanks

**Comment by MichaelAquilina** [comment]
@dcecile @glebmikulko alternatively to renaming the file, could you check if instead changing your plugins variable as follows?

```
plugins=(autoswitch_virtualenv $plugins)
```

**Comment by glebmikulko** [comment]
@MichaelAquilina It works but you should also change `git clone` command in `README.md` (for oh-my-zsh):  
`git clone "https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv.git" "$ZSH_CUSTOM/plugins/autoswitch-virtualenv"` should become `git clone "https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv.git" "$ZSH_CUSTOM/plugins/autoswitch_virtualenv"` (with underscore)

**Comment by MichaelAquilina** [comment]
:+1: thanks for the feedback @glebmikulko
