### ISSUE TITLE
osx - readme fix - brew install pyenv-virtualenvwrapper?

### ISSUE THREAD

**Issue by johndpope** [MichaelAquilina/zsh-autoswitch-virtualenv#8]
brew install virtualenvwrapper
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

**Error: No available formula with the name "virtualenvwrapper"**
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
This similarly named formula was found:
pyenv-virtualenvwrapper
To install it, run:
  brew install pyenv-virtualenvwrapper

brew install pyenv-virtualenvwrapper?

**Comment by MichaelAquilina** [comment]
I do not have a Mac so I (wrongly) assumed it was just `virtualenvwrapper`. Could you try that out? If you like you could open a PR fixing the README once you confirm it :)

**Comment by MichaelAquilina** [comment]
Updated the README @johndpope. Closing this issue. If you see it doesnt work, let me know :)
