### ISSUE TITLE
Instructions and prompt integration

### ISSUE THREAD

**Issue by rnc** [MichaelAquilina/zsh-autoswitch-virtualenv#81]
# Issue Details

Please provide the following details when opening an issue:

## Operating System (uname -a)
Fedora 29
## zsh version (zsh --version)
5.6.2

## autoswitch-virtualenv version (echo "$AUTOSWITCH_VERSION")
1.8.0

## How is zsh-you-should-use installed?

- [ ] zplug
- [ ] oh-my-zsh
- [ ] Antigen
- [x] Other (please specify) : Manual installation from source.

## gist link to your zshrc

It would be useful if it also stated normal installation procedure e.g.

```
source .../zsh-autoswitch-virtualenv/autoswitch_virtualenv.plugin.zsh
```

I also use the venv name to provide a RPROMPT upon entry into a python workspace. However for deactivation I need to ```unset venv_dir venv_name venv_path venv_type``` after the deactivate command.

**Comment by MichaelAquilina** [comment]
Hi there! 

Just to be sure I understood you correctly:
* You are suggesting better installation instructions when just sourcing the plugin directly
* You found a bug where environment variables that this plugin is creating (specifically `venv_dir` `venv_name` `venv_path` `venv_type`) that are interfering with the correctness of your PROMPT display?

**Comment by rnc** [comment]
Hi
I've made a branch to better illustrate what I mean :  
https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv/compare/master...rnc:BR1

In that I've made the two changes and also modified it to also abort the search either file system root or the HOME directory.

> You are suggesting better installation instructions when just sourcing the plugin directly

Correct

> You found a bug where environment variables that this plugin is creating (specifically `venv_dir` 
> `venv_name` `venv_path` `venv_type`) that are interfering with the correctness of your PROMPT display?

Not quite. I thought it would be useful to use venv_name to define my prompt e.g.
```
                RPROMPT="%{"$'\e[0;35m'"%}$venv_name%{"$'\e[00m%}'" %T"
```
while inside a configured python environment. Unfortunately it seemed that once deactivate was called those variables were not cleared .... assuming I've understood how its mean to work :-)

**Comment by MichaelAquilina** [comment]
Ah now I understand :) You should probably be using `$(basename "$VIRTUAL_ENV")` instead!

Regarding your change, feel free to open a PR and I can review it within a PR itself. The changes look reasonable to me at first glance.

**Comment by rnc** [comment]
PR created #82 

Ah yes, thanks!  Interestingly I see `activate` alters PS1 which I hadn't realised as I was using PROMPT which appears to override. Regardless, its potentially better not to pollute the environment after deactivation - actually I think a few more functions need 'local' for their variables (e.g. message, SWITCH_TO).

**Comment by MichaelAquilina** [comment]
> Ah yes, thanks! Interestingly I see `activate` alters PS1 which I hadn't realised as I was using PROMPT which appears to override. Regardless, its potentially better not to pollute the environment after deactivation - actually I think a few more functions need 'local' for their variables (e.g. message, SWITCH_TO).

There are probably some wins we can make in terms of preventing variables from leaking into a user's environment. Some are needed to be available globally however (there is no such thing as "private" to a script in zsh if you are sourcing it)

**Comment by rnc** [comment]
+1, agreed, all `*AUTOSWITH*` variables I _think_ need to be public, but most other things don't need to be? I've updated PR to discuss this there :-)

**Comment by rnc** [comment]
Closing as #82 is merged.
