### ISSUE TITLE
Multiple requirements and aliased rm

### ISSUE THREAD

**Issue by rnc** [MichaelAquilina/zsh-autoswitch-virtualenv#85]
# Issue Details

Please provide the following details when opening an issue:

## Operating System (uname -a)
4.20.14-200.fc29.x86_64

## zsh version (zsh --version)
5.6.2

## autoswitch-virtualenv version (echo "$AUTOSWITCH_VERSION")
1.9.0

## How is zsh-you-should-use installed?

- [ ] zplug
- [ ] oh-my-zsh
- [ ] Antigen
- [x] Other (please specify)

## Steps to reproduce the issue

1. Calls to rm are non-qualified which means that if rm is aliased (e.g. `alias rm='rm -i'`) the script won't complete. I think they should be fully qualified i.e. `/bin/rm`

2. If a repository has multiple `requirements.txt` - for example a top level one for runtime dependencies and one in a subdirectory for e.g. documentation generation dependencies then it will only load one. If the loop was `for requirements in **/requirements.txt` then it would load them all.

3. It _may_ be useful to give an example of how extra arguments such as `mkvenv --system-site-packages` ; this is extremely handy as it prevents unnecessary duplication.

**Comment by MichaelAquilina** [comment]
I assume the problems listed in 1/2/3 are all unrelated to each other?

1: could you please elaborate? I'm not sure I understand the issue. Is it that calls to the absolute path of the `rm` binary do not get detected?

2: Never ran into a project with this structure, but happy to follow that format as it doesn't break any other functionality. Could you point to an example repo where we can see this?

3. Perhaps we can provide a link to the `virtualenv` documentation which lists all these options and recommend a few useful ones?

**Comment by rnc** [comment]
Yeah , they were so small I just rolled them up for discussion purposes :-)

1. I have in my local ZSH env, rm aliased to 'rm -i'. As the call to rm is not fully qualified it hits the alias which causes issues. If it was fully qualified it would ignore the alias.

2. Sure. See https://github.com/cekit/cekit/ (and the docs subdirectory). 

3. Agreed!

**Comment by rnc** [comment]
( I can send PRs for all of the issues of course :-) )

**Comment by MichaelAquilina** [comment]
These all look like reasonable improvements to the project. Feel free to open PRs for them. Please keep them separate so that they are easier to review and merge individually :)
