### ISSUE TITLE
Setup.py and development

### ISSUE THREAD

**Issue by rnc** [MichaelAquilina/zsh-autoswitch-virtualenv#86]
# Issue Details

Please provide the following details when opening an issue:

## Operating System (uname -a)
4.20.14-200.fc29.x86_64

## zsh version (zsh --version)
5.6.2

## autoswitch-virtualenv version (echo "$AUTOSWITCH_VERSION")
1.9.0

## How is zsh-you-should-use installed?

- [ ] zplug
- [ ] oh-my-zsh
- [ ] Antigen
- [x ] Other (please specify)

## Steps to reproduce the issue

Currently can install the local repository if it sees a setup.py. I have found its more useful for development to do `pip install -e .`. Should this be an option as well?

**Comment by MichaelAquilina** [comment]
Wasn't aware of the `-e .` option to be perfectly honest. What are the specific benefits of using the `-e` option?

**Comment by rnc** [comment]
I found http://codumentary.blogspot.com/2014/11/python-tip-of-year-pip-install-editable.html a good explanation. There is also https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs 

I found it very useful as it means I can run/edit/debug the application without reinstalling.

I suppose it could be an option e.g.
```
       if [[ -f "$PWD/setup.py" ]]; then
  -        printf "Found a ${PURPLE}setup.py${NORMAL} file. Install dependencies? [y/N]: "
  +        printf "Found a ${PURPLE}setup.py${NORMAL} file. Install dependencies ${PURPLE}IN DEVELOP MODE${NORMAL}? [y/N]: "
  +        read ans
  +
  +        if [[ "$ans" = "y" || "$ans" = "Y" ]]; then
  +            pip install -e .
  +        elif
  +        then
  +            printf "Found a ${PURPLE}setup.py${NORMAL} file. Install dependencies [y/N]: "
               read ans
   
               if [[ "$ans" = "y" || "$ans" = "Y" ]]; then
                   pip install .
               fi
           fi
```

**Comment by MichaelAquilina** [comment]
Considering these are just symlinks, I would just say lets just make it the default. I don't see any large downsides to making all installs editable, and it's probably expected behaviour for most users to be honest. The change is quite simple so feel free to also try this out and open a PR!

**Comment by rnc** [comment]
I would agree that it would make sense to make it the default. I a _slightly_ concerned because its a user-visible change in behaviour with no way to customise it. I could perhaps say that 'if AUTOSWITCH_PIPINSTALL=[EDITABLE|FULL] is set then that can change the method' ?

**Comment by MichaelAquilina** [comment]
Happy to make this an option.

Are there any obvious downsides to making this the default?

**Comment by rnc** [comment]
I suppose it depends upon whether someone is developing the python project in question or just wanting to use it. I would have thought, for general usage they might want to install it without a virtualenv so it is generally available ( i.e. by using `pip install -U --user <project>` ). Hard to predict .... ;-)
