### ISSUE TITLE
Update README to make Pipenv support more clear

### ISSUE THREAD

**Issue by MichaelAquilina** [MichaelAquilina/zsh-autoswitch-virtualenv#96]

**Comment by ConstantinoSchillebeeckxSimpleRose** [comment]
I'd appreciate some help on this front! I've setup a project with `pipenv install`, when I navigate into a folder within this project, the virtual environment unloads.

**Comment by MichaelAquilina** [comment]
First off apologies for the delayed response - I was away for Xmas holidays.

`pipenv` support should work out of the box without doing anything. If you have a project setup and have run `pipenv install` on that project - then it should automatically reactivate the next time you enter that directory.

There *is* a bug right now where the first time you run `pipenv install` it does not activate the virtual env right away. Moving directories should solve this.

To be clear, you shouldnt need to jump through all those hoops you added in your EDIT.

**Comment by ConstantinoSchillebeeckxSimpleRose** [comment]
I've reverted the change to my `~/.zshrc` and done the following:
![image](https://user-images.githubusercontent.com/44036468/71679834-246c5580-2d4e-11ea-8b1a-ebe43b6a5d03.png)


As you can see:
- no `.venv` is generated
- virtual environment unloads when moving into directory located in project

Am I doing something wrong?

**Comment by MichaelAquilina** [comment]
Ah I see where the misunderstanding lies. Perhaps I should document this behaviour better in the README.

When using `pipenv` a `venv` file is not created as it is not needed. Instead the virtual environment from pipenv itself will be used. As you can see in your prompts, the `tmp` virtual environment is being correctly activated and deactivated.

Does that make sense?

**Comment by ConstantinoSchillebeeckxSimpleRose** [comment]
So is it expected behavior that, when I move into a subdirectory (like `/tmp/docs` shown above) the virtual environment disables? I would have expected that the environment stay loaded. It certainly behaves that way when using `mkvenv`.

I'm curious, why is `.venv` not needed?

**Comment by MichaelAquilina** [comment]
> So is it expected behavior that, when I move into a subdirectory (like /tmp/docs shown above) the virtual environment disables? 

No, that's a bug. Would you mind opening an issue with anything else you've seen in it?

> I'm curious, why is .venv not needed?

`.venv` is essentially a marker that lets this plugin know when to activate virtual environments automatically. When working with `pipenv` we don't need this because it's enough to check 1) is there a Pipfile 2) does pipenv have an associated virtualenv.

You can see the logic here: https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv/blob/b9aed8de91ca6bf50f39cb738d475e220e715277/autoswitch_virtualenv.plugin.zsh#L153-L159

**Comment by MichaelAquilina** [comment]
Fix in #120

**Comment by MichaelAquilina** [comment]
@ConstantinoSchillebeeckxSimpleRose I've updated the README and fixed the bug you described when moving to subdirectories in pipenv projects. Let me know if that helps or if it needs more clarity :)

**Comment by ConstantinoSchillebeeckxSimpleRose** [comment]
Fantastic; looks like everything works!
